# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 600)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.withdraw_head_label = QtWidgets.QLabel(self.centralwidget)
        self.withdraw_head_label.setGeometry(QtCore.QRect(120, 20, 131, 31))
        self.withdraw_head_label.setObjectName("withdraw_head_label")
        
        self.withdraw_estTime_label = QtWidgets.QLabel(self.centralwidget)
        self.withdraw_estTime_label.setGeometry(QtCore.QRect(10, 80, 361, 71))
        self.withdraw_estTime_label.setObjectName("withdraw_estTime_label")
        
        self.withdraw_rem_client_label = QtWidgets.QLabel(self.centralwidget)
        self.withdraw_rem_client_label.setGeometry(QtCore.QRect(40, 180, 201, 41))
        self.withdraw_rem_client_label.setObjectName("withdraw_rem_client_label")
        
        self.withdraw_rem_client_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.withdraw_rem_client_lcd.setGeometry(QtCore.QRect(240, 185, 81, 31))
        self.withdraw_rem_client_lcd.setObjectName("withdraw_rem_client_lcd")
        
        self.withdraw_ovall_estTime_label = QtWidgets.QLabel(self.centralwidget)
        self.withdraw_ovall_estTime_label.setGeometry(QtCore.QRect(60, 250, 231, 51))
        self.withdraw_ovall_estTime_label.setObjectName("withdraw_ovall_estTime_label")
        
        self.m_label1 = QtWidgets.QLabel(self.centralwidget)
        self.m_label1.setGeometry(QtCore.QRect(170, 300, 141, 21))
        self.m_label1.setObjectName("m_label1")
        
        self.service_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.service_comboBox.setGeometry(QtCore.QRect(530, 485, 200, 41))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        
        self.service_comboBox.setFont(font)
        self.service_comboBox.setEditable(False)
        self.service_comboBox.setDuplicatesEnabled(False)
        self.service_comboBox.setObjectName("service_comboBox")
        self.service_comboBox.addItem("")
        self.service_comboBox.addItem("")
        self.service_comboBox.addItem("")
        
        self.service_label = QtWidgets.QLabel(self.centralwidget)
        self.service_label.setGeometry(QtCore.QRect(220, 480, 341, 51))
        self.service_label.setObjectName("service_label")
        
        ###################################
        self.add_queue_button = QtWidgets.QPushButton(self.centralwidget , clicked = lambda: add_queue_func())
        self.add_queue_button.setGeometry(QtCore.QRect(740, 490, 181, 31))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        
        self.add_queue_button.setFont(font)
        self.add_queue_button.setObjectName("add_queue_button")
        
        self.withdraw_simu_button = QtWidgets.QPushButton(self.centralwidget , clicked = lambda: simu_func(0))
        self.withdraw_simu_button.setGeometry(QtCore.QRect(130, 350, 93, 28))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.withdraw_simu_button.setFont(font)
        self.withdraw_simu_button.setObjectName("withdraw_simu_button")
        
        self.deposit_estTime_label = QtWidgets.QLabel(self.centralwidget)
        self.deposit_estTime_label.setGeometry(QtCore.QRect(450, 80, 361, 71))
        self.deposit_estTime_label.setObjectName("deposit_estTime_label")
        
        self.m_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.m_label_2.setGeometry(QtCore.QRect(610, 300, 141, 21))
        self.m_label_2.setObjectName("m_label_2")
        
        self.deposit_rem_client_label = QtWidgets.QLabel(self.centralwidget)
        self.deposit_rem_client_label.setGeometry(QtCore.QRect(480, 180, 201, 41))
        self.deposit_rem_client_label.setObjectName("deposit_rem_client_label")
        
        self.deposit_rem_client_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.deposit_rem_client_lcd.setGeometry(QtCore.QRect(680, 185, 81, 31))
        self.deposit_rem_client_lcd.setObjectName("deposit_rem_client_lcd")
        
        self.deposit_simu_button = QtWidgets.QPushButton(self.centralwidget , clicked = lambda: simu_func(1))
        self.deposit_simu_button.setGeometry(QtCore.QRect(570, 350, 93, 28))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.deposit_simu_button.setFont(font)
        self.deposit_simu_button.setObjectName("deposit_simu_button")
        
        self.Deposit_head_label = QtWidgets.QLabel(self.centralwidget)
        self.Deposit_head_label.setGeometry(QtCore.QRect(560, 20, 131, 31))
        self.Deposit_head_label.setObjectName("Deposit_head_label")
        
        self.deposit_ovall_estTime_label = QtWidgets.QLabel(self.centralwidget)
        self.deposit_ovall_estTime_label.setGeometry(QtCore.QRect(500, 250, 231, 51))
        self.deposit_ovall_estTime_label.setObjectName("deposit_ovall_estTime_label")
        
        self.general_estTime_label = QtWidgets.QLabel(self.centralwidget)
        self.general_estTime_label.setGeometry(QtCore.QRect(880, 80, 361, 71))
        self.general_estTime_label.setObjectName("general_estTime_label")
        
        self.m_label3 = QtWidgets.QLabel(self.centralwidget)
        self.m_label3.setGeometry(QtCore.QRect(1050, 300, 141, 21))
        self.m_label3.setObjectName("m_label3")
        
        self.general_head_label = QtWidgets.QLabel(self.centralwidget)
        self.general_head_label.setGeometry(QtCore.QRect(1000, 20, 131, 31))
        self.general_head_label.setObjectName("general_head_label")
        
        self.general_rem_client_label = QtWidgets.QLabel(self.centralwidget)
        self.general_rem_client_label.setGeometry(QtCore.QRect(920, 180, 201, 41))
        self.general_rem_client_label.setObjectName("general_rem_client_label")
        
        self.general_ovall_estTime_label = QtWidgets.QLabel(self.centralwidget)
        self.general_ovall_estTime_label.setGeometry(QtCore.QRect(940, 250, 231, 51))
        self.general_ovall_estTime_label.setObjectName("general_ovall_estTime_label")
        
        self.general_simu_button = QtWidgets.QPushButton(self.centralwidget , clicked = lambda: simu_func(2))
        self.general_simu_button.setGeometry(QtCore.QRect(1010, 350, 93, 28))
        
        font = QtGui.QFont()
        font.setPointSize(12)
        
        self.general_simu_button.setFont(font)
        self.general_simu_button.setObjectName("general_simu_button")
        
        self.general_rem_client_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.general_rem_client_lcd.setGeometry(QtCore.QRect(1120, 185, 81, 31))
        self.general_rem_client_lcd.setObjectName("general_rem_client_lcd")
        
        self.withdraw_ovall_time_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.withdraw_ovall_time_lcd.setGeometry(QtCore.QRect(90, 295, 71, 31))
        self.withdraw_ovall_time_lcd.setObjectName("withdraw_ovall_time_lcd")
        
        self.deposit_ovall_time_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.deposit_ovall_time_lcd.setGeometry(QtCore.QRect(530, 295, 71, 31))
        self.deposit_ovall_time_lcd.setObjectName("deposit_ovall_time_lcd")
        
        self.general_ovall_time_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.general_ovall_time_lcd.setGeometry(QtCore.QRect(970, 295, 71, 31))
        self.general_ovall_time_lcd.setObjectName("general_ovall_time_lcd")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.withdraw_clients = 0
        self.deposit_clients = 0
        self.general_clients = 0
        
 


        def simu_func(service) : 
            
            if service ==  0 :
                if self.withdraw_clients != 0 :
                    self.withdraw_clients = self.withdraw_clients - 1
                    self.withdraw_rem_client_lcd.setProperty("intValue", self.withdraw_clients)

                    time = self.withdraw_clients * 5
                    self.withdraw_ovall_time_lcd.setProperty("intValue", time)

            elif service ==  1 :
                if self.deposit_clients !=0 :
                    self.deposit_clients = self.deposit_clients - 1
                    self.deposit_rem_client_lcd.setProperty("intValue", self.deposit_clients)

                    time = self.deposit_clients * 5
                    self.deposit_ovall_time_lcd.setProperty("intValue", time)
  
            else :
                if self.general_clients != 0 :
                    self.general_clients = self.general_clients - 1
                    self.general_rem_client_lcd.setProperty("intValue", self.general_clients)

                    time = self.general_clients * 15
                    self.general_ovall_time_lcd.setProperty("intValue", time)



        def add_queue_func() : 
            service = self.service_comboBox.currentIndex()
            
            if service ==  0 :

                self.withdraw_clients = self.withdraw_clients + 1
                self.withdraw_rem_client_lcd.setProperty("intValue", self.withdraw_clients)

                time = self.withdraw_clients * 5
                self.withdraw_ovall_time_lcd.setProperty("intValue", time)

            elif service ==  1 :

                self.deposit_clients = self.deposit_clients + 1
                self.deposit_rem_client_lcd.setProperty("intValue", self.deposit_clients)

                time = self.deposit_clients * 5
                self.deposit_ovall_time_lcd.setProperty("intValue", time)
  
            else :

                self.general_clients = self.general_clients + 1
                self.general_rem_client_lcd.setProperty("intValue", self.general_clients)

                time = self.general_clients * 15
                self.general_ovall_time_lcd.setProperty("intValue", time)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.withdraw_head_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">Withdraw</span><span style=\" font-size:14pt; font-weight:600; color:#00007d;\"/></p></body></html>"))
        self.withdraw_estTime_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Estimated time for the current client is </span></p><p align=\"center\"><span style=\" font-size:12pt;\">5</span><span style=\" font-size:12pt;\"> minutes</span></p></body></html>"))
        self.withdraw_rem_client_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:12pt; color:#202124; background-color:transparent;\">R</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#202124; background-color:transparent;\">emaining clients </span></p></body></html>"))
        self.withdraw_ovall_estTime_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Overall estimated time is </span></p></body></html>"))
        self.m_label1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\"> minutes</span></p></body></html>"))
        self.service_comboBox.setItemText(0, _translate("MainWindow", "Withdraw"))
        self.service_comboBox.setItemText(1, _translate("MainWindow", "Deposit"))
        self.service_comboBox.setItemText(2, _translate("MainWindow", "General service"))
        self.service_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#a80909;\">Please select a service</span></p></body></html>"))
        self.add_queue_button.setText(_translate("MainWindow", "Add to the queue"))
        self.withdraw_simu_button.setText(_translate("MainWindow", "Simulate"))
        self.deposit_estTime_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Estimated time for the current client is </span></p><p align=\"center\"><span style=\" font-size:12pt;\">5</span><span style=\" font-size:12pt;\"> minutes</span></p></body></html>"))
        self.m_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\"> minutes</span></p></body></html>"))
        self.deposit_rem_client_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:12pt; color:#202124; background-color:transparent;\">R</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#202124; background-color:transparent;\">emaining clients </span></p></body></html>"))
        self.deposit_simu_button.setText(_translate("MainWindow", "Simulate"))
        self.Deposit_head_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">Deposit</span></p></body></html>"))
        self.deposit_ovall_estTime_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Overall estimated time is </span></p></body></html>"))
        self.general_estTime_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Estimated time for the current client is </span></p><p align=\"center\"><span style=\" font-size:12pt;\">15</span><span style=\" font-size:12pt;\"> minutes</span></p></body></html>"))
        self.m_label3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\"> minutes</span></p></body></html>"))
        self.general_head_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">General</span></p></body></html>"))
        self.general_rem_client_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><a name=\"tw-target-text\"/><span style=\" font-family:\'inherit\'; font-size:12pt; color:#202124; background-color:transparent;\">R</span><span style=\" font-family:\'inherit\'; font-size:12pt; color:#202124; background-color:transparent;\">emaining clients </span></p></body></html>"))
        self.general_ovall_estTime_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Overall estimated time is </span></p></body></html>"))
        self.general_simu_button.setText(_translate("MainWindow", "Simulate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
